### ISSUE TITLE
Add instructions / example to run Corteza with Traefik

### ISSUE THREAD

**Issue by beevelop** [cortezaproject/corteza-docs#1]
The currently available documentation only refers to Jwilder's `nginx-proxy` as a reverse proxy. For some users, it might also be interesting to see an example with Traefik. Using Traefik only requires to add the external network (like it is done with the `proxy` network) and adding some labels to the container:
```yml
  labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:corteza.example.com"
    - "traefik.docker.network=traefik_default"
    - "traefik.port=1337"
```

**Comment by darh** [comment]
Can you make a PR with this example?

**Comment by tjerman** [comment]
@darh Are we planning on doing this? If not I'll just close it for now.

**Comment by darh** [comment]
Not beyond mentioning it in the docs. And again - if someone who know Traefik is willing to make a PR we can accept it.
