### ISSUE TITLE
Describe project structure

### ISSUE THREAD

**Issue by marcfargas** [cortezaproject/corteza-docs#10]
Hi,

Though the documentation has a brief overview of the project structure, there are a gazillion repositories in the `cortezaproject` org here in Github.

A brief index of what is what would be awesome. At least to have some idea of where to go looking for stuff :)

**Comment by tjerman** [comment]
Hey, Thanks for the feedback!

There will be more updates/additions to the corteza-docs repo since the next release is just around the corner.

In the meantime, if you have any questions, you can ask them on our community instance (https://latest.cortezaproject.org/messaging)
