### ISSUE TITLE
Cleanup your RFC's

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-docs#105]
We've (partially) opened quite a few of them.

* Cleanup the ones that are still in the RFC stage;
* The rest should be discarded/merged into the main documentations;

**Comment by darh** [comment]
Cleanedup and ready to merge (and placed in the right location).

- `rfc-record-value-expr`
- `rfc-feature-labels`

**Comment by darh** [comment]
Others not ready yet...

**Comment by tjerman** [comment]
Obsolete issue
