### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by zayn008** [cortezaproject/corteza-docs#135]
The installation guide for this project is an absolute joke. Tedious, messy, not a full guide.

**Comment by zmija** [comment]
Hi @zayn008,

Thanks for your feedback. Please keep in mind we look at the project and the code practically every day and we openly admit it's very possible some things seem obvious to us, but definitely not to devs who are not yet that familiar with Corteza. 

Can you please share more details on how far you get in the process of installation and what is the blocker? We're here to help.

Cheers!

**Comment by zmija** [comment]
Hi @zayn008,

I'm just sending a kind reminder if you can please share with us where you got stuck with the installation? We would really like to sort this out and also improve the guide per your feedback.

Looking forward to your reply

**Comment by zayn008** [comment]
Hello! Thanks for response and sorry if I was over critical, I just spend hours researching couldn’t get my head around the installation

so I have no idea where to begin with installation, looking at all the guides they seem to make assumptions I have no idea about, as in it assumes I have an environment ready for installation, there’s is no A-Z installation guide

**Comment by tjerman** [comment]
@zayn008 hi; no harm as long as the criticism is constructive and helps with improvements. We're still in the process of experimenting and figuring out just how we want the documentation to be, so some parts may seem like a bit of a mess.

If you could help me out a bit and perhaps write down an outline of how you would like to see the "how to deploy Corteza" part structured. I am trying to redesign the DevOps guide but I am not yet sure how exactly I'd like to have it. Perhaps someone else's perspective could help me out.

---

#### To help you out with the instalation:
You're interested about the [DevOps Guide](https://docs.cortezaproject.org/corteza-docs/2020.12/dev-ops-guide/index.html), the deployment examples to be precise.

If you wish to setup a quick local installation (for a demo, development) you are interested in [this setup](https://docs.cortezaproject.org/corteza-docs/2020.12/dev-ops-guide/deployment/demo-mysql.html).
If you wish to deploy it on a server (any sort of server deployment; production, staging, ...) you are looking at either [this one - PostgreSQL database](https://docs.cortezaproject.org/corteza-docs/2020.12/dev-ops-guide/deployment/prod-pgsql.html) or [this one - MySQL database](https://docs.cortezaproject.org/corteza-docs/2020.12/dev-ops-guide/deployment/prod-mysql.html)

Regardless of which one you pick, the setup is the same; create a new directory dedicated for the package (let's say we have it at `~/projects/corteza`), create a `docker-compose.yaml` and an `.env` file; copy the provided examples into those two files.

Run with docker-compose and that is it.

What the setup guides assume is that you have Docker and Docker Compose (if not there is a [little section for that](https://docs.cortezaproject.org/corteza-docs/2020.12/dev-ops-guide/docker-compose.html)); as well as a reverse-proxy such as [Nginx proxy](https://docs.cortezaproject.org/corteza-docs/2020.12/dev-ops-guide/deployment/prod-proxy-nginx.html).
The last logical assumptions that we do is that you already have some infrastructure that is able to run Corteza (a desktop, laptop, server), you have a domain (when deploying on a server); that sort of things.

---

Let me know if that worked for you!

**Comment by zayn008** [comment]
Hi, so I did attempt to install on a VM and it was fairly straightforward however I struggled to install it on my server as I encountered several issues but I assume this is because of conflicting software's, in the end I hired a freelancer to complete the install

I do think a YouTube tutorial should be made on how to install though as the simplicity of it actually makes it seem complicated, to me at least haha... I kept thinking I was missing something and unsure
