### ISSUE TITLE
Create a draft regarding Swagger API documentation

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-docs#137]
* Outline how it works (there is a separate tool that converts our endpoint definitions to openAPI definitions; things like that).
* Outline how to add a new one.

Please have this ready by 2021.3 release.

**Comment by Fajfa** [comment]
https://github.com/cortezaproject/corteza-docs/commit/03cc57e94417f307e57356b40ff4da6ed6122c42

**Comment by anborg** [comment]
Using rest-api, how to create Case? 
Using rest-api, how to create Contact? 

Is there a way to use grpc api to create a Case?
Is there a way to use grpc api to create a Contact?

Case
![image](https://user-images.githubusercontent.com/56970398/110003230-2defa580-7ce4-11eb-9b36-f2f426778de7.png)
Contact
![image](https://user-images.githubusercontent.com/56970398/110003542-78712200-7ce4-11eb-85af-b6cc9fb69dec.png)

**Comment by tjerman** [comment]
> Using rest-api, how to create Case?
> Using rest-api, how to create Contact?

Under the hood, contacts and cases are the same things -- records.
You can use this draft example (it should still work, but I haven't gotten around to updating it yet - that is why it's not released to the docs currently) -- https://github.com/cortezaproject/corteza-docs/tree/2021.3.x/src/modules/integrator-guide/pages/accessing-corteza/examples/compose (there is a `record-create.adoc` file)

> Is there a way to use grpc api to create a Case?
> Is there a way to use grpc api to create a Contact?

No and no. Currently, only the HTTP API is exposed. We might add other interfaces in future releases but don't quote me on this.

___

If the above doesn't answer your question, please open a new ticket.
