### ISSUE TITLE
Refactor the DevOps guide

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-docs#139]
I feel that the structure & content are a bit confusing to newcomers. I am also not entirely set on how I would like to structure this, so @darh I might need a hand.

**Comment by c-nv-s** [comment]
It may also help you to note that following your installation guide for production fails to build:
[https://docs.cortezaproject.org/corteza-docs/2020.12/dev-ops-guide/deployment/prod-pgsql.html](https://docs.cortezaproject.org/corteza-docs/2020.12/dev-ops-guide/deployment/prod-pgsql.html)

```
# docker-compose up -d
...                                
Pulling corredor (cortezaproject/corteza-server-corredor:2020.20.0)...          
ERROR: manifest for cortezaproject/corteza-server-corredor:2020.20.0 not found  
```
tried changing corredor to "latest" and setting VERSION=2020.20.2
```
# export VERSION=2020.20.2
# docker-compose up -d
...
Pulling server (cortezaproject/corteza-server:2020.20.2)...
ERROR: manifest for cortezaproject/corteza-server:2020.20.2 not found
```
it only seems to build when you set VERSION=latest for everything either via the .env file or via the export command in the shell

```
# export VERSION=latest
# docker-compose up -d
...
Status: Downloaded newer image for cortezaproject/corteza-server:latest
Creating cortezaprod_db_1       ... done
Creating cortezaprod_corredor_1 ... done
Creating cortezaprod_server_1   ... done
```

it might be useful to go through and retest the installation instructions.
And maybe also advise on publishing/exposing which ports from container to the host as an alternative approach for users who have their own reverse proxy or certificate solution in place and therefore do not need to rely on
jwilder/nginx-proxy
jrcs/letsencrypt-nginx-proxy-companion

At the moment the **Important Note** section seems to end on an incomplete sentence/cliffhanger...
"If you prefer and use a different method to forward HTTP traffic to your Docker containers"
...Maybe it's just me, but I was expecting some additional advice to follow this sentence.

UPDATE: my mistake I had a typo in the date - I should have used 2020.12 and not 2020.20

**Comment by tjerman** [comment]
Thanks for the feedback and suggestions. I'm about 35% done with the latest documentation refactoring so I can take a look at incorporating your feedback into the 2021.3 version.
