### ISSUE TITLE
Sync data between CRM Suite and Service Solution?

### ISSUE THREAD

**Issue by zayn008** [cortezaproject/corteza-docs#146]
I've just installed this software and assumed these 2 applications were supposed to sync, information such as Cases, Accounts and Knowledge Base? However I've noticed the 2 do not sync, is this possible as I plan to use the CRM Suite for our sales team and the Service Solution to our support staff

**Comment by tjerman** [comment]
@zayn008 applications (namespaces) have independent data scope and can't just access one another.

I see two options:
1. you implement a few automation scripts to sync -- [this should help you out](https://docs.cortezaproject.org/corteza-docs/2020.12/integrator-guide/extensions/index.html)
2. you implement a new application which implements all of the bits required by the system (sales stuff and support stuff) and both roles use the same application.

**Comment by zayn008** [comment]
@tjerman I was always under the impression the Service Desk was just an Extension of the CRM, but thanks for clarifying. After having a deeper look, I realised the CRM has pretty much all the features of the Service Desk, so I'll probably just use the second solution and add a Service Solution Tab to the CRM with everything I need :) 

Appreciate your help
