### ISSUE TITLE
Document sub workflows

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza-docs#304]
A sub-section [here](https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/automation/workflows/index.html); document the new sub-workflows addition.

- [x] how to configure a sub-workflow and how it needs to look like
- [x] how to call sub-workflows and how can I pass arguments into execution and collect return values

**Comment by tjerman** [comment]
WIP PR https://github.com/cortezaproject/corteza-docs/pull/307
