### ISSUE TITLE
Make changes to documentation in regards to mono-repo migration

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza-docs#305]
- [x] https://github.com/cortezaproject/corteza/issues/531
- [x] https://github.com/cortezaproject/corteza-docs/issues/317
- [x] https://github.com/cortezaproject/corteza-docs/issues/318
- [x] https://github.com/cortezaproject/corteza-docs/issues/320

Some info:
https://github.com/cortezaproject/corteza-server/discussions/437

**Comment by tjerman** [comment]
We should address this through December.
I'll try to address the more important ones in this sprint and the rest when time comes.

**Comment by tjerman** [comment]
* The README is waiting for a review to see if it's _markety_ enough
* the repository overview is just about done (final reviews)
* the developer guide reworking is going to be done later or probably not at all (the more I look at it the less it makes sense)

**Comment by tjerman** [comment]
Removed `- [ ] https://github.com/cortezaproject/corteza-docs/issues/319` from the list; can be considered at a later point; no need for now
