### ISSUE TITLE
Document bulk record create request

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza-docs#349]
## Notes
- Email: API Bulk Record Insert
- This task is from an email thread and that's the reason why Tomaž will take over this. (Also explains the lack of more context for this issue)

## TODO
- [ ] document feature
- [ ] update client when finished

**Comment by tjerman** [comment]
Someone already documented this to the point where it's sufficient so I'll mark it off as done.
The [contents are here](https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/accessing-corteza/examples/compose-records-bulk.html)
