### ISSUE TITLE
Document page block magnification feature

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-docs#375]
## About

Page block magnification allows users to focus/expand specific page blocks over the entire page.

The contents should be placed in **a new file** in the [compose-configuration section](https://github.com/cortezaproject/corteza-docs/tree/2023.3.x/src/modules/integrator-guide/pages/compose-configuration).

The contents should:

* Outline what the feature is, what it can be used for, and some use-cases,
* Outline how to enable/configure the feature,
* Outline what the different page block magnifications do (provide screenshots on how they look like).

Original issue https://github.com/cortezaproject/corteza/issues/450

## Important

Any screenshots **should** [follow our guidelines](https://docs.cortezaproject.org/corteza-docs/2022.9/developer-guide/documentation/annotations.html) -- from taking the screenshot to annotating it.

**Comment by katrinDY** [comment]
For today: add remaining documentation and submit for code review

**Comment by katrinDY** [comment]
for today: address comments from PR and re-submit for review
