### ISSUE TITLE
Document page block auto refresh feature

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-docs#384]
Page block auto refresh lets configurators pull and show new data when the content behind it changes.

The documentation should [go here](https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/compose-configuration/index.html)

- [x] Document how to enable it and what configuration options are available
- [x] Document what page blocks support it and any plans to support the ones which are currently not
- [ ] Provide an example

Original issue https://github.com/cortezaproject/corteza/issues/466

**Comment by tjerman** [comment]
Will get a PR going for me in a bit

**Comment by katrinDY** [comment]
For today: finish task

**Comment by katrinDY** [comment]
for today: address comments from PR and resubmit for code review

**Comment by EmmyMay** [comment]
For today: continue to address the review comments.

**Comment by katrinDY** [comment]
For today: address comments and resubmit for review
