### ISSUE TITLE
Document page block tabs

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-docs#385]
Page block tabs let users show multiple page blocks inside a single page block.
The new page block enables you to show more information on a smaller surface.

The documentation should [go here](https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/compose-configuration/page-blocks.html) (for the reference) and [here](https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/compose-configuration/index.html) (for configuration, usage)

- [x] Document how to configure and use the page block
- [x] Add it to the page block reference
- [x] Provide an example

Original issue https://github.com/cortezaproject/corteza/issues/452

**Comment by tjerman** [comment]
Will hop onto this one after #384

**Comment by katrinDY** [comment]
For today: continue working on this. Timebox to 3h

**Comment by KinyaElGrande** [comment]
For today: continue working on this. Timebox another 3h

**Comment by EmmyMay** [comment]
putting this away for now as I am experiencing some issues with images that is blocking progress.

**Comment by katrinDY** [comment]
for today: add annotations and figure out why nested images don't work

**Comment by katrinDY** [comment]
for today: address review comments

**Comment by katrinDY** [comment]
for today: timebox blocker to 1h

**Comment by katrinDY** [comment]
for today: sync with Tomaž to resolve Docker blocker

**Comment by katrinDY** [comment]
for today: address comments and submit for review

**Comment by katrinDY** [comment]
for today: address comments and submit for review

**Comment by katrinDY** [comment]
for today: sync with Tomaž on review comments and address them

**Comment by EmmyMay** [comment]
This has been updated @tjerman

**Comment by EmmyMay** [comment]
This has been updated to reflect the latest review comments
