### ISSUE TITLE
Add Compose record value sanitization & validation

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-docs#47]
[Take this as a base](https://docs.cortezaproject.org/corteza-docs/2020.12/developer-guide/compose/index.html)

* [ ] Update value validation (also include validation from automation scripts).
* [ ] Add value sanatization -- what, where, how.

**Comment by darh** [comment]
This is explained in the RFC. I'll leave you to refactor it out to the proper place.

**Comment by tjerman** [comment]
Won't be including low-level development content for the time being
