### ISSUE TITLE
Refactor the integrator guide to be straight to the point

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-docs#64]
[Take this as a base](https://docs.cortezaproject.org/corteza-docs/2020.9/integrator-guide/index.html)

These are the main bits that we need to cover:

* [x] Terminology;
* [x] Defining a data model;
* [x] Creating extensions;
* [x] Deploying extensions;
* [x] Debugging extensions;
* [x] Examples; tips and tricks for all areas;

* [x] Permission tips;

Rels:
* [x] https://github.com/cortezaproject/corteza-docs/issues/16
* [x] https://github.com/cortezaproject/corteza-docs/issues/13

In regards to deploying extensions:

* [x] How to use them with docker containers.
* [x] How to use them outside for local development.
* [x] How do you use NPM dependencies.
* [x] Overwriting existing scripts.
* [x] Tips and tricks for easier deployments (git, scp, rsync, ...).

**Note**: Provide a high-level overview; try to omit as many low-level things as possible.
Low-level stuff should go into the developer guide.

**Comment by balakumar1001** [comment]
Do we have timeline for this refactor? I am struggling to add new extensions with current documentation. I understand the concept of server and client side scripts from current documentation, however there is no details on how to add a new one.

**Comment by tjerman** [comment]
Hey; this should be available here in the next week or so, and available on the documentation page by the 2020.12 release (end of December).

I will try to push the first draft of the refactor by the end of this week. If you're in a hurry and have concrete questions, jot them down here and I'll answer as soon as I am able.

**Comment by tjerman** [comment]
@balakumar1001 [see here](https://github.com/cortezaproject/corteza-docs/blob/80426d0535fd43f825a7a524a689cc6fb1a96a4c/src/modules/ROOT/pages/integrator-guide/extensions/deploying.adoc) for the draft regarding deploying automation scripts. It's still a draft but it should help you deploy your scripts. It will be finalized (along with the rest of the integrator docs) through this week.

**Comment by balakumar1001** [comment]
> @balakumar1001 [see here](https://github.com/cortezaproject/corteza-docs/blob/80426d0535fd43f825a7a524a689cc6fb1a96a4c/src/modules/ROOT/pages/integrator-guide/extensions/deploying.adoc) for the draft regarding deploying automation scripts. It's still a draft but it should help you deploy your scripts. It will be finalized (along with the rest of the integrator docs) through this week.

@tjerman Thanks for the update.. We will explore this draft version
