### ISSUE TITLE
getting error when try to add new lead "Could not create this record: not connected"

### ISSUE THREAD

**Issue by avasni** [cortezaproject/corteza-docs#8]
I have deploy and try to add new lead while getting following error "Could not create this record: not connected". used all four docker-compose in deploy folder and also chaged mysql version. 

Thanks,

**Comment by darh** [comment]
@avasni I'll take a look right away.

**Comment by darh** [comment]
@avasni:

 - can you list the 4 containers you use
 - what was the reason to change the mysql version

**Comment by avasni** [comment]
![screen1](https://user-images.githubusercontent.com/26759337/68576500-2c1d2580-0494-11ea-8fd3-2d2260c80d6b.png)
@darh Thanks for quick reply. 

I am running following compose file in local.

https://github.com/cortezaproject/corteza-docs/tree/master/deploy/docker-compose/example-2019-07-os.com

I have also deploy on cloud server using following docker-compose file.

https://github.com/cortezaproject/corteza-docs/blob/master/deploy/docker-compose/simple/docker-compose.yml

I was getting below log in docker-compose db log so I tried with different version of database.

db_1      | mbind: Operation not permitted

Let me know if I am missing some setting because I tried to run all compose file provided in deploy folder of doc repo.

Thanks,

**Comment by darh** [comment]
Ok, I see.

Please add corredor service to your docker-compose config.

Instructions are here:
https://github.com/cortezaproject/corteza-docs/blob/master/deploy/docker-compose/corredor.md

_Looks like our frontend alert eats up half of the original error message._



Let me know if this works for you.

**Comment by avasni** [comment]
@darh Thanks,

I am running below docker-compose file but getting same error. 

services:
  corredor:
    environment:
      CORREDOR_ADDR: corredor:80
      CORREDOR_API_BASE_URL_COMPOSE: http://localhost:10080/compose
      CORREDOR_API_BASE_URL_MESSAGING: http://localhost:10080/messaging
      CORREDOR_API_BASE_URL_SYSTEM: http://localhost:10080/system
      CORREDOR_DEBUG: "true"
      CORREDOR_ENABLED: "true"
      CORREDOR_LOG_ENABLED: "true"
      CORREDOR_LOG_LEVEL: trace
      CORREDOR_LOG_PRETTY: "true"
    image: cortezaproject/corteza-server-corredor
    restart: on-failure
  db:
    environment:
      MYSQL_DATABASE: corteza
      MYSQL_PASSWORD: oscom-tutorial
      MYSQL_ROOT_PASSWORD: supertopsecret
      MYSQL_USER: corteza
    image: percona:8.0
  server:
    environment:
      DB_DSN: corteza:oscom-tutorial@tcp(db:3306)/corteza?collation=utf8mb4_general_ci
      PROVISION_SETTINGS_AUTH_FRONTEND_URL_BASE: http://localhost:20080
      VIRTUAL_HOST: localhost:10080
    image: cortezaproject/corteza-server:latest
    ports:
    - 10080:80/tcp
  webapp:
    environment:
      API_BASEURL: localhost:10080
      MONOLITH_API: 1
    image: cortezaproject/corteza-webapp:latest
    ports:
    - 20080:80/tcp
version: '2.0'

Does I missing some basic installation instruction ? I am following the below link to start on local machine.

https://cortezaproject.org/documentation/installation-guide/

Thanks,

**Comment by darh** [comment]
Might be best if you check this example here:
https://github.com/cortezaproject/corteza-docs/tree/master/deploy/docker-compose/simple

`CORREDOR_*` variables should be accessible from both, corredor and server services (containers). So it would be smart to move them to `.env` file and ref this file from the config (as you can see [here](https://github.com/cortezaproject/corteza-docs/blob/master/deploy/docker-compose/simple/docker-compose.yml#L21)).

btw: next time when you paste a chunk of code like this config here you can use 3 backticks ([markdown format](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax)) that formats that block of text

**Comment by avasni** [comment]
@darh Thanks for support. It's working now. :)
